version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      # Ignore TailwindCSS major version 4+ (stay on v3.x)
      - dependency-name: 'tailwindcss'
        versions: ['[4.0.0,)']

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker images
  - package-ecosystem: 'docker'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker Compose
  - package-ecosystem: 'docker-compose'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'

  # Enable version updates for Dev containers Features
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
