version: 2
updates:
  # Enable version updates for npm dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker images
  - package-ecosystem: 'docker'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'

  # Enable version updates for Docker Compose
  - package-ecosystem: 'docker-compose'
    directory: '/.devcontainer'
    schedule:
      interval: 'weekly'

  # Enable version updates for Dev containers Features
  - package-ecosystem: 'devcontainers'
    directory: '/'
    schedule:
      interval: 'weekly'
