name: 📝 Documentation
description: Report issues with documentation or suggest improvements
title: '📝 [Docs]: '
labels: ['documentation', 'triage']
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve our documentation! Clear documentation benefits everyone.

        **This template is for:**
        - Reporting unclear or missing documentation
        - Suggesting documentation improvements
        - Reporting broken links or outdated information

  - type: dropdown
    id: doc_type
    attributes:
      label: Documentation Type
      description: What type of documentation needs attention?
      options:
        - README.md
        - Contributing Guidelines
        - Security Policy
        - Code Comments
        - API Documentation
        - Setup/Installation Guide
        - Development Workflow
        - Brand Guidelines
        - Blog Content Guidelines
        - Component Documentation
        - Other (please specify)
    validations:
      required: true

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of documentation issue is this?
      options:
        - Missing information
        - Outdated information
        - Unclear instructions
        - Broken link
        - Typo/Grammar error
        - Formatting issue
        - Translation needed
        - Accessibility improvement
        - SEO improvement
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: |
        Where is the documentation issue located?
        Please provide:
        - File path or URL
        - Section/heading name
        - Line numbers (if applicable)
      placeholder: |
        File: /path/to/file.md
        Section: "Getting Started"
        Lines: 25-30
        URL: https://viscalyx.se/docs/example
    validations:
      required: true

  - type: textarea
    id: current_content
    attributes:
      label: Current Content
      description: What does the current documentation say? (Copy and paste the relevant section)
      render: markdown
      placeholder: |
        Paste the current documentation content here...

  - type: textarea
    id: issue_description
    attributes:
      label: Issue Description
      description: What's wrong with the current documentation?
      placeholder: |
        Describe the issue clearly:
        - What's confusing or unclear?
        - What information is missing?
        - What needs to be corrected?
    validations:
      required: true

  - type: textarea
    id: suggested_improvement
    attributes:
      label: Suggested Improvement
      description: How should the documentation be improved?
      render: markdown
      placeholder: |
        Provide your suggested changes:
        - What should be added, removed, or changed?
        - How should it be restructured?
        - What examples or clarifications would help?
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who would benefit from this documentation improvement?
      multiple: true
      options:
        - New contributors
        - Experienced developers
        - Content creators
        - Site administrators
        - End users
        - Translators
        - Designers
    validations:
      required: true

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: |
        Any additional context that would help improve the documentation?
        - Related issues or discussions
        - Examples from other projects
        - Screenshots (if UI-related)
      placeholder: |
        Additional context:
        - Related issues: #123
        - Example from: [project name]
        - Screenshots: [attach files or paste URLs]

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this documentation issue hasn't been reported before
          required: true
        - label: I have read the current documentation thoroughly
          required: true
        - label: I have checked that the information is indeed incorrect or missing
          required: true
        - label: I am willing to help improve the documentation if needed
          required: false
