interface:
  display_name: "Review Comments Validator"
  short_description: "Validate AI reviewer findings before patching code"
  default_prompt: "Use $review-comments-validator to verify each review finding against current code, fix only valid ones, and summarize rejected findings with reasons."
