name: Spell Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run spell check
      run: npm run spell:check
      
    - name: Comment on PR if spelling errors found
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '❌ **Spell check failed!** Please run `npm run spell:check` locally to see the issues and fix them before merging.'
          })
